import {
  HomeIcon,
  UserGroupIcon,
  DocumentTextIcon,
  CalendarDaysIcon,
  EyeIcon,
  CheckCircleIcon,
  ClockIcon,
  PauseIcon,
  PlusIcon,
  UsersIcon,
  MapIcon,
  BuildingOfficeIcon,
  CreditCardIcon,
  TruckIcon,
  ChartBarIcon,
  Cog6ToothIcon,
  DocumentChartBarIcon,
} from "@heroicons/react/24/outline";
import { NAV_TYPE_ITEM, NAV_TYPE_COLLAPSE } from "constants/app.constant";
import { ROUTES } from "app/router/routes";

// New flat navigation structure with expandable dropdowns
export const navigation = [
  {
    id: "dashboard",
    type: NAV_TYPE_ITEM,
    path: ROUTES.DASHBOARD.HOME,
    title: "Dashboard",
    transKey: "nav.dashboard",
    Icon: HomeIcon,
  },
  {
    id: "lead-management",
    type: NAV_TYPE_COLLAPSE,
    title: "Lead Management",
    transKey: "nav.leadManagement",
    Icon: UserGroupIcon,
    childs: [
      {
        id: "leads.all",
        path: ROUTES.LEADS.ALL,
        type: NAV_TYPE_ITEM,
        title: "All Leads",
        transKey: "nav.leads.all",
        Icon: EyeIcon,
      },
      {
        id: "leads.fresh",
        path: ROUTES.LEADS.FRESH,
        type: NAV_TYPE_ITEM,
        title: "Fresh Leads",
        transKey: "nav.leads.fresh",
        Icon: ClockIcon,
      },
      {
        id: "leads.converted",
        path: ROUTES.LEADS.CONVERTED,
        type: NAV_TYPE_ITEM,
        title: "Converted Leads",
        transKey: "nav.leads.converted",
        Icon: CheckCircleIcon,
      },
      {
        id: "leads.postponed",
        path: ROUTES.LEADS.POSTPONED,
        type: NAV_TYPE_ITEM,
        title: "Postponed Leads",
        transKey: "nav.leads.postponed",
        Icon: PauseIcon,
      },
    ],
  },
  {
    id: "quotations-management",
    type: NAV_TYPE_COLLAPSE,
    title: "Quotations",
    transKey: "nav.quotationsManagement",
    Icon: DocumentTextIcon,
    childs: [
      {
        id: "quotations.all",
        path: ROUTES.QUOTATIONS.ALL,
        type: NAV_TYPE_ITEM,
        title: "All Quotations",
        transKey: "nav.quotations.all",
        Icon: EyeIcon,
      },
    ],
  },
  {
    id: "booking",
    type: NAV_TYPE_COLLAPSE,
    title: "Booking",
    transKey: "nav.booking",
    Icon: CalendarDaysIcon,
    childs: [
      {
        id: "bookings.all",
        path: ROUTES.BOOKINGS.ALL,
        type: NAV_TYPE_ITEM,
        title: "All Bookings",
        transKey: "nav.bookings.all",
        Icon: EyeIcon,
      },
      {
        id: "bookings.confirmed",
        path: ROUTES.BOOKINGS.CONFIRMED,
        type: NAV_TYPE_ITEM,
        title: "Confirmed Bookings",
        transKey: "nav.bookings.confirmed",
        Icon: CheckCircleIcon,
      },
      {
        id: "bookings.pending",
        path: ROUTES.BOOKINGS.PENDING,
        type: NAV_TYPE_ITEM,
        title: "Pending Bookings",
        transKey: "nav.bookings.pending",
        Icon: ClockIcon,
      },
      {
        id: "bookings.create",
        path: ROUTES.BOOKINGS.CREATE,
        type: NAV_TYPE_ITEM,
        title: "Create Booking",
        transKey: "nav.bookings.create",
        Icon: PlusIcon,
      },
    ],
  },
  {
    id: "employee-management",
    type: NAV_TYPE_COLLAPSE,
    title: "Employee Management",
    transKey: "nav.employeeManagement",
    Icon: UsersIcon,
    childs: [
      {
        id: "employees.all",
        path: ROUTES.EMPLOYEES.ALL,
        type: NAV_TYPE_ITEM,
        title: "Employee List",
        transKey: "nav.employees.list",
        Icon: EyeIcon,
      },
      {
        id: "employees.create",
        path: ROUTES.EMPLOYEES.CREATE,
        type: NAV_TYPE_ITEM,
        title: "Add New Employee",
        transKey: "nav.employees.create",
        Icon: PlusIcon,
      },
    ],
  },
  {
    id: "travel-management",
    type: NAV_TYPE_COLLAPSE,
    title: "Travel Management",
    transKey: "nav.travelManagement",
    Icon: MapIcon,
    childs: [
      {
        id: "travel.itineraries",
        path: ROUTES.ITINERARIES.ALL,
        type: NAV_TYPE_ITEM,
        title: "Itineraries",
        transKey: "nav.travel.itineraries",
        Icon: DocumentTextIcon,
      },
      {
        id: "travel.hotel-vouchers",
        path: ROUTES.TRAVEL.HOTEL_VOUCHERS,
        type: NAV_TYPE_ITEM,
        title: "Hotel Vouchers",
        transKey: "nav.travel.hotelVouchers",
        Icon: BuildingOfficeIcon,
      },
      {
        id: "travel.customers",
        path: ROUTES.TRAVEL.CUSTOMERS,
        type: NAV_TYPE_ITEM,
        title: "Customers",
        transKey: "nav.travel.customers",
        Icon: UserGroupIcon,
      },
      {
        id: "travel.upcoming-trips",
        path: ROUTES.TRAVEL.UPCOMING_TRIPS,
        type: NAV_TYPE_ITEM,
        title: "Upcoming Trips",
        transKey: "nav.travel.upcomingTrips",
        Icon: CalendarDaysIcon,
      },
      {
        id: "travel.on-trips",
        path: ROUTES.TRAVEL.ON_TRIPS,
        type: NAV_TYPE_ITEM,
        title: "ON Trips",
        transKey: "nav.travel.onTrips",
        Icon: TruckIcon,
      },
      {
        id: "travel.payment",
        path: ROUTES.TRAVEL.PAYMENT,
        type: NAV_TYPE_ITEM,
        title: "Payment",
        transKey: "nav.travel.payment",
        Icon: CreditCardIcon,
      },
    ],
  },
  {
    id: "reports-settings",
    type: NAV_TYPE_COLLAPSE,
    title: "Reports & Settings",
    transKey: "nav.reportsSettings",
    Icon: ChartBarIcon,
    childs: [
      {
        id: "reports-settings.reports",
        path: ROUTES.REPORTS_SETTINGS.REPORTS,
        type: NAV_TYPE_ITEM,
        title: "Reports",
        transKey: "nav.reportsSettings.reports",
        Icon: DocumentChartBarIcon,
      },
      {
        id: "reports-settings.analytics",
        path: ROUTES.REPORTS_SETTINGS.ANALYTICS,
        type: NAV_TYPE_ITEM,
        title: "Analytics",
        transKey: "nav.reportsSettings.analytics",
        Icon: ChartBarIcon,
      },
      {
        id: "reports-settings.settings",
        path: ROUTES.REPORTS_SETTINGS.SETTINGS,
        type: NAV_TYPE_ITEM,
        title: "Settings",
        transKey: "nav.reportsSettings.settings",
        Icon: Cog6ToothIcon,
      },
    ],
  },
];

export { baseNavigation } from "./baseNavigation";
